### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by glynnsmith** [AtomLinter/linter-jshint#226]
Hey. Getting this error when enabling linting within inline `<script>` tags:

    TypeError: Cannot read property 'length' of undefined
    TypeError: Cannot read property 'length' of undefined
        at TextBuffer.module.exports.TextBuffer.lineLengthForRow (C:\Users\Glynn\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:457:29)
        at Object.<anonymous> (C:/Users/Glynn/.atom/packages/linter-jshint/lib/main.js:141:57)
        at [object Generator].next (native)
        at step (C:\Users\Glynn\.atom\packages\linter-jshint\lib\main.js:3:273)
        at process._tickCallback (node.js:368:9)

My `config.cson`:
````
"*":
  "atom-jshint": {}
  "autocomplete-plus":
    enableAutoConfirmSingleSuggestion: false
  "color-picker":
    abbreviateValues: true
    automaticReplace: true
    randomColor: false
  core:
    audioBeep: false
    closeEmptyWindows: false
    destroyEmptyPanes: false
    disabledPackages: [
      "wrap-guide"
      "pigments"
      "minimap-pigments"
    ]
    openEmptyEditorOnStart: false
    themes: [
      "one-dark-ui"
      "base16-tomorrow-dark-theme"
    ]
  editor:
    fontFamily: "input mono light"
    fontSize: 12
    invisibles: {}
    lineHeight: 1.65
    normalizeIndentOnPaste: true
    preferredLineLength: 110
    scrollPastEnd: true
    softWrap: true
    zoomFontWhenCtrlScrolling: false
  "highlight-line": {}
  jslint:
    useFoldModeAsDefault: true
    validateOnChange: true
    validateOnSave: false
  linter:
    errorPanelHeight: 201
    showErrorTabLine: true
  "linter-htmlhint": {}
  "linter-jshint":
    lintInlineJavaScript: true
  "linter-scss-lint": {}
  minimap:
    plugins:
      linter: true
      pigments: true
  "one-dark-ui":
    layoutMode: "Spacious"
  pigments:
    delayBeforeScan: 2
    extendAutocompleteToColorValue: true
    extendAutocompleteToVariables: true
    groupPaletteColors: "by file"
    supportedFiletypes: [
      "*.html"
      "*.css"
      "*.scss"
    ]
  welcome:
    showOnStartup: false
````

I have no `.jshintrc`
